[tool.poetry]
name = "welcomebot"
description = "Greets alcoholics"
version = "1.0.0"
authors = ["Blindfolded Surgery <team@blindfolded.surgery>"]
license = "MIT"
packages = [{ from = "src", include = "app" }]

[tool.poetry.dependencies]
certifi = "2024.6.2"
python = "~3.12"
python-telegram-bot = "21.3"
sentry-sdk = "^2.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"
mypy = "^1.4.0"
pytest = "^8.0.0"
ruff = "0.4.8"
types-requests = "^2.31.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
warn_unused_ignores = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false

[tool.ruff]
extend-select = [
    "I001",
]

[tool.ruff.isort]
known-first-party = ["app"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
