---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: welcome-secrets
spec:
  encryptedData:
    TELEGRAM_TOKEN: AgAJmodW6eahUu96/kV2YqkhWwp8ApY4cgpLDYqE3XdIFO1/z4EazxNRYJRrgCfbbbL2Q+LkdM+x6XVGdIYBVbV7ylc+hFFRtBjTjZH9Ivi2TPePXRhx3DX0npOKr3Ws0HD9b72wzHhr23nx8VzmmHuN0/LnMl0jPtVYsdFrDVVDViBL7v9PX6EgngjqfIDLaJ870Q3ShEBgYpLdrfIi+qjvpBwkKfynAIbdhoJvygHI6kBENhqnvPMRdrQNyk+IUSoC0gvx2cHVSq+qQUcksqKcRIBFatqeRcyf9FKYpGooSVSR2/AAPrBUZZYg4OJFdR1b2Bg40JoDYl2hQevKTQMe9Ez4AMZ7Q3f5immsr0nmA0vOyrvhU3ssLmHIzZjOJIejOEd5ZTXmf2GvTUGoA7lOHE+7eHIkrrrD3RcRzevQGnuA/5k//CWMlh9qpkTR4Yc1YLYkmtN92NjqjvvCfRaIrKQzrbO8ePdgnea4BJrug8W3Xv7HjkhRPOKDOI+ei6C7mSLO1cUbqRVFdjZvVfLy9+bkXee66UdJnquh8w4YqaKEye36BQ3hX4EJ1YVxT5xMrTs+uOy35BxPvzvk9qm2OQ8e/WFRNRjYFRj28EEFW19FCBAQu0fsoYIQB1eB5Y94irs8HIZUy9AmimGC+zNn9O5C/W3nk4AgD2wso0Ww0V3qakI9g/2+WmMeQQcti2nXdMU+H7a1nlx5kp+oB1c9lM8jmoIWhxBnRjLgPolm17drKwLP1R7dwld6OVdx
  template:
    metadata:
      name: welcome-secrets
    type: Opaque
