---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: welcome-secrets
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: welcome-secrets
  dataFrom:
    - find:
        path: "WELCOME_"
      rewrite:
        - regexp:
            source: "WELCOME_(.+)"
            target: "$1"
