---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-update-handler
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: update-handler
  template:
    metadata:
      labels:
        app: update-handler
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          envFrom:
            - secretRef:
                name: welcome-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bob
spec:
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: welcome-update-handler
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats-headless.nats-system.svc.cluster.local:8222"
        account: "$G"
        stream: "telegram-updates"
        consumer: "welcome-bot"
