---
apiVersion: v1
kind: Service
metadata:
  name: welcome-update-handler
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: welcome-update-handler
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: update-handler
  serviceName: update-handler
  template:
    metadata:
      labels:
        app: update-handler
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          envFrom:
            - secretRef:
                name: welcome-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
